export const LANGUAGES = new Map<string, string>([
  ["js", "Javascript"],
  ["mjs", "Javascript (Module)"],
  ["jsx", "Javascript (JSX)"],
  ["tsx", "Typescript (TSX)"],
  ["mdx", "Markdown (MDX)"],
  ["php", "PHP"],
  ["sql", "SQL"],
  ["bash", "Bash/Shell"],
  ["cs", "C#"],
  ["fs", "F#"],
  ["kt", "Kotlin"],
  ["lua", "Lua"],
  ["txt", "Plain Text"],
  ["ts", "TypeScript"],
  ["dart", "Dart"],
  ["py", "Python"],
  ["r", "R"],
  ["go", "Go"],
  ["html", "HTML"],
  ["css", "CSS"],
  ["json", "JSON"],
  ["rs", "Rust"],
  ["rb", "Ruby"],
  ["hs", "Haskell"],
  ["md", "Markdown"],
  ["c", "C"],
  ["cpp", "C++"],
  ["java", "Java"],
  ["swift", "Swift"],
  ["vb", "Visual Basic (.Net)"],
  ["asm", "Assembly"],
  ["s", "Assembly"],
  ["ex", "Elixir"],
  ["exs", "Elixir (Script)"],
  ["pl", "Perl"],
  ["zig", "Zig"],
  ["yaml", "YAML"],
  ["toml", "TOML"],
  ["zsh", "ZShell"],
  ["clj", "Clojure"],
]);