export const languages: {[k: string]: string} = {
  "js": "Javascript",
  "mjs": "Javascript (Module)",
  "jsx": "Javascript (JSX)",
  "tsx": "Typescript (TSX)",
  "php": "PHP",
  "sql": "SQL",
  "bash": "Bash/Shell",
  "cs": "C#",
  "kt": "Kotlin",
  "lua": "Lua",
  "txt": "Plain Text",
  "ts": "TypeScript",
  "dart": "Dart",
  "py": "Python",
  "go": "Go",
  "html": "HTML",
  "css": "CSS",
  "json": "JSON",
  "rs": "Rust",
  "rb": "Ruby",
  "hs": "Haskell",
  "md": "Markdown",
  "c": "C",
  "cpp": "C++",
  "java": "Java",
  "swift": "Swift",
  "vb": "Visual Basic (.Net)",
  "asm": "Assembly",
  "s": "Assembly",
  "ex": "Elixir",
  "exs": "Elixir (Script)"
};